#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating rectangle=854x480+540+270
bspc rule -a mpv state=floating rectangle=1024x576+440+270
bspc rule -a Lxappearance state=floating

# startup 
polybar -r & 
picom --backend glx -b &  
feh --bg-fill ~/Pictures/Wallpapers/tlouanime.png &
xrdb ~/.Xresources &
greenclip daemon &
xset r rate 300 50

bspc config focus_follows_pointer     true
bspc config pointer_modifier          alt
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
bspc config click_to_focus            any
bspc config pointer_motion_interval   0.5

# colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#b4befe"
bspc config focused_border_color	"#b4befe"
bspc config presel_feedback_color	"#b4befe"
